### ISSUE TITLE
alibaba插件在Eclipse Mars.2 Release (4.5.2) 版本下不能使用

### ISSUE THREAD

**Issue by chshyin** [alibaba/p3c#118]
插件可以安装成功，选中项目后点击Switch Language和Alibaba Code Guidelines按钮没有反应
查看eclipse的workspace\.metadata\.log日志后发现以下错误
`
Caused by: java.util.ServiceConfigurationError: net.sourceforge.pmd.lang.Language: Provider net.sourceforge.pmd.lang.java.JavaLanguageModule not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.sourceforge.pmd.lang.LanguageRegistry.<init>(LanguageRegistry.java:29)
	at net.sourceforge.pmd.lang.LanguageRegistry.<clinit>(LanguageRegistry.java:19)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.<init>(AbstractJavaRule.java:19)
	at com.alibaba.p3c.pmd.lang.java.rule.AbstractAliRule.<init>(AbstractAliRule.java:31)
	at com.alibaba.p3c.pmd.lang.java.rule.concurrent.ThreadPoolCreationRule.<init>(ThreadPoolCreationRule.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.sourceforge.pmd.RuleSetFactory.parseSingleRuleNode(RuleSetFactory.java:405)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:319)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:272)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:202)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:197)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:359)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:317)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:272)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:202)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:197)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:184)
	at com.alibaba.smartfox.eclipse.SmartfoxActivator$Companion.createRuleSets(SmartfoxActivator.kt:135)
	at com.alibaba.smartfox.eclipse.SmartfoxActivator.start(SmartfoxActivator.kt:51)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 65 more
`

**Comment by xusheng1987** [comment]
我的直接卡死

**Comment by battlesteed** [comment]
我的也是卡出翔,jpa插件已经卸载了,不是jpa循环调用bug

**Comment by battlesteed** [comment]
eclipseneon和目前最新的eclipseoxygn都不行

**Comment by chshyin** [comment]
已查明是由于和pmd插件冲突，导致ali插件启动不起来。
卸载已有的pmd插件，即可正常使用。
已知的和1.11.0版本pmd插件冲突，暂时不知和哪个版本pmd插件兼容

**Comment by xusheng1987** [comment]
我也没有安装pmd插件，还是卡

**Comment by dxxfire** [comment]
安装PMD插件导致不能用的可以考虑改一下插件安装的顺序，先安装p3c插件之后再安装PMD-eclipse插件就可以了。我用的Spring Tool Suite，3.9.2.RELEASE，UI报错，org.eclipse.core.runtime.CoreException: Plug-in com.alibaba.smartfox.eclipse.plugin was unable to load class com.alibaba.smartfox.eclipse.ui.InspectionResultView.改下安装顺序后就可以使用了。
