### ISSUE TITLE
IDEA内存异常占用（Windows平台）

### ISSUE THREAD

**Issue by Cy0941** [alibaba/p3c#168]
IDEA版本及系统如下：IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0。通过鼠标悬停进入查看规约建议修改信息，IDEA占用内存从1G左右猛增到9G左右，系统卡死；关闭IDEA，内存占用恢复正常

**Comment by SeanCai** [comment]
@Cy0941 哪条规则触发的？ Help -> Show Log 看看具体日志吧。

**Comment by Cy0941** [comment]
下面是部分日志（其余全部是规则校验）
2017-11-10 10:34:56,436 [5373842]   INFO - ection.AliPmdInspectionInvoker - elapsed 122ms to to apply rule ThreadShouldSetNameRule for file ****/ICustomerProductService.java 
2017-11-10 10:34:56,460 [5373866]   INFO - ection.AliPmdInspectionInvoker - elapsed 23ms to to apply rule IbatisMethodQueryForListRule for file ****/ICustomerProductService.java 
2017-11-10 10:34:56,461 [5373867]   INFO - ection.AliPmdInspectionInvoker - elapsed 0ms to to apply rule PojoMustOverrideToStringRule for file ****/ICustomerProductService.java 
2017-11-10 10:34:56,494 [5373900]   INFO - ection.AliPmdInspectionInvoker - elapsed 30ms to to apply rule ClassCastExceptionWithToArrayRule for file ****/ICustomerProductService.java 
2017-11-10 10:34:56,499 [5373905]   INFO - ection.AliPmdInspectionInvoker - elapsed 1ms to to apply rule AvoidNewDateGetTimeRule for file ****/ICustomerProductService.java 
2017-11-10 10:35:38,539 [5415945]   WARN - ellij.openapi.ui.DialogWrapper - Stale listener: com.intellij.ide.ui.laf.LafManagerImpl$OurPopupFactory$1@1a0d5868 
2017-11-10 10:36:08,272 [5445678]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1 
2017-11-10 10:39:12,984 [5630390]   WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 1 
2017-11-10 10:39:13,054 [5630460]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: D:\JetBrains\IntelliJIDEA\bin\fsnotifier64.exe 
2017-11-10 10:39:17,931 [5635337]   INFO - .server.BuildMessageDispatcher - 远程主机强迫关闭了一个现有的连接。 
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
由于IDEA占用内存差不多达到12G左右了只能强制关闭了；还请能够排查一下问题，谢谢

**Comment by Cy0941** [comment]
@SeanCai 
以下是上午发生问题的部分日志（其余全部是规则校验）
2017-11-10 10:34:56,436 [5373842] INFO - ection.AliPmdInspectionInvoker - elapsed 122ms to to apply rule ThreadShouldSetNameRule for file ****/ICustomerProductService.java
2017-11-10 10:34:56,460 [5373866] INFO - ection.AliPmdInspectionInvoker - elapsed 23ms to to apply rule IbatisMethodQueryForListRule for file ****/ICustomerProductService.java
2017-11-10 10:34:56,461 [5373867] INFO - ection.AliPmdInspectionInvoker - elapsed 0ms to to apply rule PojoMustOverrideToStringRule for file ****/ICustomerProductService.java
2017-11-10 10:34:56,494 [5373900] INFO - ection.AliPmdInspectionInvoker - elapsed 30ms to to apply rule ClassCastExceptionWithToArrayRule for file ****/ICustomerProductService.java
2017-11-10 10:34:56,499 [5373905] INFO - ection.AliPmdInspectionInvoker - elapsed 1ms to to apply rule AvoidNewDateGetTimeRule for file ****/ICustomerProductService.java
2017-11-10 10:35:38,539 [5415945] WARN - ellij.openapi.ui.DialogWrapper - Stale listener: com.intellij.ide.ui.laf.LafManagerImpl$OurPopupFactory$1@1a0d5868
2017-11-10 10:36:08,272 [5445678] INFO - ide.actions.ShowFilePathAction -
Exit code 1
2017-11-10 10:39:12,984 [5630390] WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 1
2017-11-10 10:39:13,054 [5630460] INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: D:\JetBrains\IntelliJIDEA\bin\fsnotifier64.exe
2017-11-10 10:39:17,931 [5635337] INFO - .server.BuildMessageDispatcher - 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
at sun.nio.ch.SocketDispatcher.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:745)
由于IDEA占用内存差不多达到12G左右了只能强制关闭了；还请能够排查一下问题，谢谢

**Comment by SeanCai** [comment]
@Cy0941 后面有复现吗

**Comment by pzsoftchen** [comment]
我也碰到内存飙升导致idea卡死的情况
