### ISSUE TITLE
UndefineMagicConstantRule规则扫描报错

### ISSUE THREAD

**Issue by oggboy** [alibaba/p3c#189]
`if (extra.equals("{}"))`
使用UndefineMagicConstantRule规则扫描上面该行代码时会报错。
错误信息如下：
java.lang.IllegalArgumentException: can't parse argument number: 
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1420)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:363)
	at java.text.MessageFormat.format(MessageFormat.java:835)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.cleanup(AbstractRuleViolationFactory.java:24)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.addViolation(AbstractRuleViolationFactory.java:32)
	at net.sourceforge.pmd.lang.rule.AbstractRule.addViolationWithMessage(AbstractRule.java:381)
	at com.alibaba.p3c.pmd.lang.java.rule.AbstractAliRule.addViolationWithMessage(AbstractAliRule.java:57)
	at com.alibaba.p3c.pmd.lang.java.rule.constant.UndefineMagicConstantRule.visit(UndefineMagicConstantRule.java:70)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:31)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:25)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:306)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:149)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:80)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:47)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:79)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1418)
	... 21 more

**Comment by xuantan** [comment]
谢谢反馈，问题已解决，本周会发布新版本的插件。
