### ISSUE TITLE
UndefineMagicConstantRule规则扫描仍报错

### ISSUE THREAD

**Issue by oggboy** [alibaba/p3c#207]
if (s.charAt(0) != '{' || s.charAt(n-1) != '}')
使用UndefineMagicConstantRule规则扫描上面该行代码时会报错。

java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(Unknown Source)
	at java.text.MessageFormat.<init>(Unknown Source)
	at java.text.MessageFormat.format(Unknown Source)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.cleanup(AbstractRuleViolationFactory.java:24)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.addViolation(AbstractRuleViolationFactory.java:32)
	at net.sourceforge.pmd.lang.rule.AbstractRule.addViolationWithMessage(AbstractRule.java:385)
	at com.alibaba.p3c.pmd.lang.java.rule.AbstractAliRule.addViolationWithMessage(AbstractAliRule.java:57)
	at com.alibaba.p3c.pmd.lang.java.rule.constant.UndefineMagicConstantRule.visit(UndefineMagicConstantRule.java:72)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:31)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:25)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:306)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:79)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by xuantan** [comment]
确认下IDE插件的版本是否是1.0.3，如果不是的话请升级到最新版本试试。

**Comment by oggboy** [comment]
p3c-pmd version 1.3.3
