### ISSUE TITLE
eclipse-plugin项目无法编译成功

### ISSUE THREAD

**Issue by yosaku01** [alibaba/p3c#228]
代码拉下来后，执行mvn -U clean install时，到最后出错误，显示错误信息
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Unable to connect to repository http://mirrors.ustc.edu.cn/eclipse/releases/juno/201206270900/artifacts.jar
        at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:428)
        at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:259)
        at org.eclipse.tycho.p2.remote.RemoteRepositoryCacheManager.createCache(RemoteRepositoryCacheManager.java:67)
..........................

**Comment by xuantan** [comment]
重试几次，或是连个VPN，这个报错信息是无法下载到jar包。
