### ISSUE TITLE
P3C-idea 项目运行报错

### ISSUE THREAD

**Issue by dinmshi** [alibaba/p3c#260]
使用 gradlew runIde 命令进行变异运行报错，插件加载失败
[     80]   WARN - .intellij.util.EnvironmentUtil - can't get shell environment 
java.lang.Exception: bin:/Users/coric/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/14.1.7/61e2cd02e2314063e9f0f3e2cf2249feeca8c128/ideaIC-14.1.7/bin
        at com.intellij.util.EnvironmentUtil.getShellEnv(EnvironmentUtil.java:150)
        at com.intellij.util.EnvironmentUtil.access$000(EnvironmentUtil.java:41)
        at com.intellij.util.EnvironmentUtil$1.call(EnvironmentUtil.java:54)
        at com.intellij.util.EnvironmentUtil$1.call(EnvironmentUtil.java:50)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[   7159]   WARN - j.ui.mac.MacMainFrameDecorator - no url bundle present. 

[  17449]  ERROR - Templates.impl.DefaultTemplate - IntelliJ IDEA 14.1.7  Build #IC-141.3058.30 
[  17449]  ERROR - Templates.impl.DefaultTemplate - JDK: 1.8.0_151 
[  17449]  ERROR - Templates.impl.DefaultTemplate - VM: Java HotSpot(TM) 64-Bit Server VM 
[  17449]  ERROR - Templates.impl.DefaultTemplate - Vendor: Oracle Corporation 
[  17449]  ERROR - Templates.impl.DefaultTemplate - OS: Mac OS X 
[  17449]  ERROR - Templates.impl.DefaultTemplate - Last Action:  

[  17449]  ERROR - Templates.impl.DefaultTemplate - Entry fileTemplates//j2ee/default.properties.ft not found in /Users/coric/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/14.1.7/61e2cd02e2314063e9f0f3e2cf2249feeca8c128/ideaIC-14.1.7/plugins/android/lib/resources_en.jar 
java.io.FileNotFoundException: Entry fileTemplates//j2ee/default.properties.ft not found in /Users/coric/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/14.1.7/61e2cd02e2314063e9f0f3e2cf2249feeca8c128/ideaIC-14.1.7/plugins/android/lib/resources_en.jar
        at com.intellij.util.io.URLUtil.openJarStream(URLUtil.java:98)
        at com.intellij.util.io.URLUtil.openStream(URLUtil.java:59)
        at com.intellij.ide.fileTemplates.impl.UrlUtil.loadText(UrlUtil.java:45)
        at com.intellij.ide.fileTemplates.impl.DefaultTemplate.loadText(DefaultTemplate.java:53)
        at com.intellij.ide.fileTemplates.impl.DefaultTemplate.<init>(DefaultTemplate.java:46)
        at com.intellij.ide.fileTemplates.impl.FileTemplatesLoader.loadDefaultsFromRoot(FileTemplatesLoader.java:183)
        at com.intellij.ide.fileTemplates.impl.FileTemplatesLoader.loadDefaultTemplates(FileTemplatesLoader.java:143)
        at com.intellij.ide.fileTemplates.impl.FileTemplatesLoader.<init>(FileTemplatesLoader.java:88)
        at com.intellij.ide.fileTemplates.impl.ExportableFileTemplateSettings.<init>(ExportableFileTemplateSettings.java:48)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.initializeInstance(ServiceManagerImpl.java:228)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter$1.compute(ServiceManagerImpl.java:216)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:207)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
        at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:32)
        at com.intellij.ide.fileTemplates.impl.ExportableFileTemplateSettings.getInstance(ExportableFileTemplateSettings.java:52)
        at com.intellij.ide.fileTemplates.impl.FileTemplateManagerImpl.<init>(FileTemplateManagerImpl.java:94)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.initializeInstance(ServiceManagerImpl.java:228)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter$1.compute(ServiceManagerImpl.java:216)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:207)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
        at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
        at com.intellij.ide.fileTemplates.FileTemplateManager.getInstance(FileTemplateManager.java:55)
        at com.intellij.codeInspection.defaultFileTemplateUsage.FileHeaderChecker.checkFileHeader(FileHeaderChecker.java:50)
        at com.intellij.codeInspection.defaultFileTemplateUsage.DefaultFileTemplateUsageInspection.checkFile(DefaultFileTemplateUsageInspection.java:65)
        at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitFile(AbstractBaseJavaLocalInspectionTool.java:98)
        at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:74)
        at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
        at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:285)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:75)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:254)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:251)
        at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
        at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
        at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
        at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
        at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
        at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
        at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by dinmshi** [comment]
请问这是什么问题呢？是我这边配置的问题吗，步骤是glone整个项目之后导入p3c-idea项目到intellij IU,然后使用提供的命令使用gradlew 变异运行
