### ISSUE TITLE
在win10系统中插件菜单不显示

### ISSUE THREAD

**Issue by ixubin** [alibaba/p3c#310]
先说问题，我有两个同事都是win10的系统，用的myeclipse2014，装完之后死活看不到插件菜单。我个人用的也是2014，不过系统是win8.1，装完之后马上就能看到。我同事也按照说明安装了jdk1.8，但是仍然不显示。
另外对README_cn.md这里面的说明提下意见：**把JDK从1.6升级到1.8**。这句话说的好模糊啊，估计很多小伙伴会看不懂。我看了其他的issues我才明白指的是eclipse启动时的环境。但是有以下问题：
1.我的myeclipse2014启动使用的是默认集成的jdk7，但是我的插件可以正常显示。
2.myeclipse2014是没法指定jdk8作为启动环境的，他支持的编译级别最大就到7
3.是不是跟win10系统有关系啊，在win8.1上很正常。

**Comment by ixubin** [comment]
!ENTRY org.eclipse.equinox.p2.repository 2 0 2018-05-24 09:54:19.813
!MESSAGE Server returned lastModified <= 0 for https://p3c.alibaba.com/plugin/eclipse/update/content.jar

!ENTRY org.eclipse.equinox.p2.repository 2 0 2018-05-24 09:54:20.987
!MESSAGE Server returned lastModified <= 0 for https://p3c.alibaba.com/plugin/eclipse/content.jar

!ENTRY org.eclipse.equinox.p2.core 4 0 2018-05-24 09:54:21.336
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://p3c.alibaba.com/plugin/eclipse.
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:128)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at com.genuitec.pulse.client.deliverypackage.runtime.ui.InProductStartup$ValidatingMetadataRepositoryManager.loadRepository(Unknown Source)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at com.genuitec.pulse.client.deliverypackage.runtime.ui.InProductStartup$ValidatingMetadataRepositoryManager.loadRepository(Unknown Source)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.io.IOException: https://p3c.alibaba.com/plugin/eclipse is not a valid repository location.
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:102)
	... 12 more
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1002 2018-05-24 09:54:21.336
!MESSAGE Unable to read repository at https://p3c.alibaba.com/plugin/eclipse.
!STACK 0
java.io.IOException: https://p3c.alibaba.com/plugin/eclipse is not a valid repository location.
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at com.genuitec.pulse.client.deliverypackage.runtime.ui.InProductStartup$ValidatingMetadataRepositoryManager.loadRepository(Unknown Source)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at com.genuitec.pulse.client.deliverypackage.runtime.ui.InProductStartup$ValidatingMetadataRepositoryManager.loadRepository(Unknown Source)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:117)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:102)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$2.runModal(PreloadingRepositoryHandler.java:83)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by SeanCai** [comment]
地址是这个 https://p3c.alibaba.com/plugin/eclipse/update

**Comment by ixubin** [comment]
这是使用离线安装包安装的，在我的win8.1系统上是正常的。
然后在win10系统上又使用上面的地址进行了一次在线安装，日志如下：
!ENTRY org.eclipse.equinox.p2.repository 2 0 2018-05-24 15:15:32.108
!MESSAGE Server returned lastModified <= 0 for https://p3c.alibaba.com/plugin/eclipse/update/artifacts.jar
!SESSION 2018-05-24 15:16:06.704 -----------------------------------------------
依然看不到菜单。
ps：从myeclipse2014的插件市场里搜到该插件，然后进行安装一样看不到菜单。
