### ISSUE TITLE
p3c-pmd能在pmd里使用吗？

### ISSUE THREAD

**Issue by Armymen** [alibaba/p3c#405]
编译p3c-pmd，把生成的p3c-pmd-1.5.0.jar放在lib目录里，运行pmd

**Comment by xuantan** [comment]
你好，可以的。

**Comment by Armymen** [comment]
在Contos上通过run.sh pmd在若干项目运行有的会报错
Exception in thread "main" java.lang.NoSuchMethodError: net.sourceforge.pmd.lang.rule.AbstractRule.setTypeResolution(Z)V
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.<init>(AbstractJavaRule.java:22)
	at com.alibaba.p3c.pmd.lang.java.rule.AbstractAliRule.<init>(AbstractAliRule.java:31)
	at com.alibaba.p3c.pmd.lang.java.rule.oop.EqualsAvoidNullRule.<init>(EqualsAvoidNullRule.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.sourceforge.pmd.RuleSetFactory.parseSingleRuleNode(RuleSetFactory.java:405)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:319)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:272)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:202)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:197)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:161)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:145)
	at net.sourceforge.pmd.RulesetsFactoryUtils.getRuleSets(RulesetsFactoryUtils.java:31)
	at net.sourceforge.pmd.RulesetsFactoryUtils.getRuleSetsWithBenchmark(RulesetsFactoryUtils.java:59)
	at net.sourceforge.pmd.PMD.doPMD(PMD.java:234)
	at net.sourceforge.pmd.PMD.run(PMD.java:499)
	at net.sourceforge.pmd.cli.PMDCommandLineInterface.run(PMDCommandLineInterface.java:167)
	at net.sourceforge.pmd.PMD.main(PMD.java:477)
有的则没有任何结果
通过java -cp p3c-pmd-1.3.5.jar则正常运行
