### ISSUE TITLE
One NullPointerException in class EnumConstantsMustHaveCommentRule

### ISSUE THREAD

**Issue by haichaoyuan** [alibaba/p3c#442]
测试代码如下：
```
public enum SortEnum implements Serializable{
    //人机对话统计_左
    /**
     * 全部
     */
    MML_ALL("全部", "all", 0),
    /**
     * 已对话的
     */
    MML_TALKED("已对话的", "talked", 1)
}
```
报错如下：
```
Caused by: java.lang.NullPointerException
	at com.alibaba.p3c.pmd.lang.java.rule.comment.EnumConstantsMustHaveCommentRule.visit(EnumConstantsMustHaveCommentRule.java:54)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:31)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:25)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:306)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:149)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:80)
```
简单分析了下原因，因为测试代码枚举类下面直接两个注释，第一个注释是两条斜杠，监测不通过，isReport 置为 true，继续走循环，在第二条注释上去获取 jjtGetParent() 就好报空指针。那么解决问题的点就在于需要忽略连续的注释，梳理了下逻辑，感觉可以改成这个样子，在EnumConstantsMustHaveCommentRule 的 visit 方法 修改代码：
```
@Override
    public Object visit(ASTCompilationUnit cUnit, Object data) {
        SortedMap<Integer, Node> itemsByLineNumber = this.orderedCommentsAndEnumDeclarations(cUnit);

        // Check comments between ASTEnumDeclaration and ASTEnumConstant.
        boolean isPreviousEnumDecl = false;
        boolean isReport = false;
        boolean tmp = false;//

        for (Entry<Integer, Node> entry : itemsByLineNumber.entrySet()) {
            Node value = entry.getValue();

            if (value instanceof ASTEnumDeclaration) {
                // 1. 类声明
                isPreviousEnumDecl = true;
            } else if (value instanceof Comment && isPreviousEnumDecl) {
                //2. 判断注释格式，是否\/**\/
                if (value instanceof SingleLineComment || value instanceof MultiLineComment) {
                    isReport = true;
//                    isPreviousEnumDecl = false;
                } else {
                    isPreviousEnumDecl = false;
                }
            } else if (isReport) {
                Node enumBody = value.jjtGetParent();
                Node enumDeclaration = enumBody.jjtGetParent();
                addViolationWithMessage(data, enumBody,
                        I18nResources.getMessage("java.comment.EnumConstantsMustHaveCommentRule.violation.msg",
                                enumDeclaration.getImage()));
                isReport = false;
                isPreviousEnumDecl = false;
            } else if (value instanceof ASTEnumConstant && isPreviousEnumDecl) {
                //这个意思是类声明(ASTEnumDeclaration)和枚举常量(ASTEnumConstant),中间没有其他属性，这里是注释
                Node enumBody = value.jjtGetParent();
                Node enumDeclaration = enumBody.jjtGetParent();
                addViolationWithMessage(data, enumBody,
                        I18nResources.getMessage("java.comment.EnumConstantsMustHaveCommentRule.violation.msg",
                                enumDeclaration.getImage()));
                isPreviousEnumDecl = false;
            } else {
                isPreviousEnumDecl = false;
            }
        }

        return super.visit(cUnit, data);
    }
```
测试可以通过，小小修改不知道还有没有其他问题，望指教。

**Comment by xuantan** [comment]
@kerie 看下这个问题

**Comment by kerie** [comment]
@haichaoyuan 测试代码我这边扫描是正确的，能否提供下完整可复现异常的代码？

**Comment by haichaoyuan** [comment]
1. 不好意思，才看到
2. 第一反应，是不是问题已经被修复，特地去拿来 https://github.com/alibaba/p3c/ 项目的 EnumConstantsMustHaveCommentRule 类跑了我的测试文件，发现问题还是有的。
3. 我的测试文件是 https://github.com/haichaoyuan/p3c/blob/master/p3c-pmd/src/test/resources/com/alibaba/p3c/pmd/lang/java/rule/comment/xml/EnumConstantsMustHaveCommentRule.xml ，你可以跑跑测试文件
4. 我的临时解决如下，https://github.com/haichaoyuan/p3c/blob/master/p3c-pmd/src/main/java/com/alibaba/p3c/pmd/lang/java/rule/comment/EnumConstantsMustHaveCommentRule.java
5. 后期，在考虑类下面直接检测是不是带星号注释会不会太简单直接暴力，其实可以允许开发任意在带星号注释前面添加斜杠注释

**Comment by kerie** [comment]
@haichaoyuan 你好，感谢反馈！
看了下你fork的代码库，可能跟alibaba的代码库差异较大，我说下我的操作步骤：
1. 下载alibaba/p3c最新代码
2. 将你的测试用例复制到alibaba/p3c工程
3. expected-problems 从 1 改成 0
4. 执行maven clean test，结果显示全部通过

**Comment by haichaoyuan** [comment]
@kerie 您好，我今天尝试了下，确实是改好了，也不知道上次为什么有问题，可能存在缓存把。

我是在6月份 fork 了一份 , 回过来看看，原来这个类已经被改了。当时老代码出现空指针的时候，解决的同时也想着，”来源于社区，服务于社区“，就哼哧哼哧赶过来提 Issue。我提的时候就去 Issue 搜索了下，没去看最新的代码，哈哈，失误，下次注意。

**Comment by kerie** [comment]
@haichaoyuan 您好，非常感谢您的反馈。我昨天也是准备基于你的代码库排查下，结果发现加了很多功能哈，赞。这个issue我先close了，欢迎下次遇到问题再提，也欢迎直接给我们提交pull request。
