### ISSUE TITLE
sonar 集成 UndefineMagicConstantRule 报错

### ISSUE THREAD

**Issue by migo2012** [alibaba/p3c#504]
java.lang.IllegalArgumentException: unknown format type: 2
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1526)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.cleanup(AbstractRuleViolationFactory.java:24)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.addViolation(AbstractRuleViolationFactory.java:32)
	at net.sourceforge.pmd.lang.rule.AbstractRule.addViolationWithMessage(AbstractRule.java:385)
	at com.alibaba.p3c.pmd.lang.java.rule.AbstractAliRule.addViolationWithMessage(AbstractAliRule.java:80)
	at com.alibaba.p3c.pmd.lang.java.rule.constant.UndefineMagicConstantRule.visit(UndefineMagicConstantRule.java:70)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:31)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:25)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43)
	at org.sonar.plugins.pmd.PmdTemplate.process(PmdTemplate.java:82)
	at org.sonar.plugins.pmd.PmdExecutor.executeRules(PmdExecutor.java:120)
	at org.sonar.plugins.pmd.PmdExecutor.executePmd(PmdExecutor.java:90)
	at org.sonar.plugins.pmd.PmdExecutor.execute(PmdExecutor.java:75)
	at org.sonar.plugins.pmd.PmdSensor.analyse(PmdSensor.java:67)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by xuantan** [comment]
你好，我们是针对sonar5.6.3这个版本进行的开发。
