### ISSUE TITLE
2个小问题

### ISSUE THREAD

**Issue by leonard99559** [alibaba/p3c#534]
1. ali-pmd.xml
在commit的时候会检测报错，原因：与xsd文件定义不符，在其中添加一个 " description "标签

2.自定义rulesets/xxx.xml时
xxx.xml中的rule标签必须添加example子标签，否则该xml文件中写多个rule的时候，idea会报错
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.p3c.idea.inspection.RuleInspectionUtils
	at com.alibaba.p3c.idea.inspection.AliPmdInspection.<init>(AliPmdInspection.kt:43)
	at ClassNamingShouldBeCamelRuleInspection.<init>(DelegatePmdInspection.kt:38)
	... 27 more

**Comment by SeanCai** [comment]
@leonard99559 hello，commit的时候检测是什么检测？
自定义rulesets试试加上语言目录rulesets/java/xxx.xml，然后规则名要以Rule结尾
