### ISSUE TITLE
DuplicateComponentKeyRegistrationException in com.alibaba.p3c.idea.config.P3cConfig duplicated

### ISSUE THREAD

**Issue by lechie** [alibaba/p3c#630]
从 IDEA 自带的 plugins > marketplace 安装完插件后，启动idea 直接崩溃退出，重试几次都不行，错误如下：
```
java.util.concurrent.CompletionException: org.picocontainer.defaults.DuplicateComponentKeyRegistrationException in com.alibaba.p3c.idea.config.P3cConfig duplicated
```
```
 - Device: Macbook pro
 - OS: macOS catelina 10.15.2
 - Idea version: 2019.3
- JRE 11.0.5+10
```
目前到 `/Users/xxx/Library/Application Support/IntelliJIdea2019.3` 文件夹下，删除了
`Alibaba Java Coding Guidelines` 文件夹后，再启动 IDEA 一切恢复正常。

**Comment by WindBruce** [comment]
遇到同样的错误

**Comment by SeanCai** [comment]
内部插件承载了其他平台能力，所以同时安装外部版本会冲突，后续有类似错误请直接找我

**Comment by iamJunPan** [comment]
> l

我的电脑没有Alibaba Java Coding Guidelines啊

**Comment by iamJunPan** [comment]
> 内部插件承载了其他平台能力，所以同时安装外部版本会冲突，后续有类似错误请直接找我

我的报错如下，按照楼上方法没有解决。 能帮忙看下么
java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key com.alibaba.p3c.idea.config.P3cConfig duplicated
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
