### ISSUE TITLE
LockShouldWithTryFinallyRule causes jvm ClassNotFoundException

### ISSUE THREAD

**Issue by yjqg6666** [alibaba/p3c#636]
**Describe the bug**
java-ali-concurrent rulesets of p3c-pmd version 2.0.1 introduces rule LockShouldWithTryFinallyRule which uses https://github.com/alibaba/p3c/blob/master/p3c-pmd/src/main/kotlin/com/alibaba/p3c/pmd/lang/java/rule/concurrent/LockShouldWithTryFinallyRule.kt.  If the machine running the pmd checking do not have kotlin support, the ClassNotFoundException would be thrown and exited.

**To Reproduce**
1. Use the latest version of PMD(downloaded from https://github.com/pmd/pmd/releases/download/pmd_releases/6.20.0/pmd-bin-6.20.0.zip) and the latest version of p3c-pmd (downloaded from  https://repo1.maven.org/maven2/com/alibaba/p3c/p3c-pmd/2.0.1/p3c-pmd-2.0.1.jar)
2. unzip the pmd-bin-6.20.0.zip and copy the p3c-pmd-2.0.1.jar into the pmd-bin-6.20.0/lib/
3. run /path/to/pmd-bin-6.20.0/bin/run.sh -dir src -rulesets java-ali-concurrent
4. got the ERROR:
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at com.alibaba.p3c.pmd.lang.java.rule.concurrent.LockShouldWithTryFinallyRule.visit(LockShouldWithTryFinallyRule.kt)
	at net.sourceforge.pmd.lang.java.ast.ASTBlock.jjtAccept(ASTBlock.java:27)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:61)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:95)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:321)
	at net.sourceforge.pmd.lang.java.ast.ASTMethodDeclaration.jjtAccept(ASTMethodDeclaration.java:36)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:61)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:95)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:141)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept(ASTClassOrInterfaceBodyDeclaration.java:44)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:61)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:95)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:136)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBody.jjtAccept(ASTClassOrInterfaceBody.java:35)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:61)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:95)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:106)
	at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceDeclaration.jjtAccept(ASTClassOrInterfaceDeclaration.java:55)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:61)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:95)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:291)
	at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:39)
	at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:61)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:95)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:266)
	at com.alibaba.p3c.pmd.lang.java.rule.AbstractAliRule.visit(AbstractAliRule.java:60)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:39)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:27)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:555)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:194)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 42 more

**Expected behavior**
Code be checked and output some warning or error on console.

**Desktop (please complete the following information):**
 - OS: 
GNU/Linux Debian bullseye/sid
 -  Kernel
    5.4.0-2-amd64 
 - p3c-pmd Version 2.0.1
 - JDK version: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
 -  **NO Kotlin installed**

**Comment by yjqg6666** [comment]
Hi team, you may check https://discuss.kotlinlang.org/t/not-able-to-run-jar-file/7943 .

**Comment by yjqg6666** [comment]
1.  append class path  "-auxclasspath /tmp/kotlin-stdlib-jdk8-1.3.50.jar " not working.
2.  copy the kotlin-stdlib-jdk8-1.3.50.jar into the lib directory not working too.

**Comment by Yuyang105** [comment]
@SeanCai 看一下哈

**Comment by songtianyi** [comment]
> The workaround is to download kotlin libraries and put them into lib directory. Now it's working verified using https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.50/kotlin-stdlib-1.3.50.jar and https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.50/kotlin-stdlib-jdk8-1.3.50.jar.

not work
把这两个文件放在classpath，还是同样的错误。

**Comment by sdttttt** [comment]
我在`2.1.1`版本和pmd的JavaAPI一起使用，没有发现这个问题。

**Comment by XenoAmess** [comment]
@yjqg6666

Hi. sounds like you should not do that.

It be no bug, but your usage for the jar is wrong...

This jar is not designed for invoke directly (like a for-all.jar or something), this jar have dependencies...

you SHOULD have all dependencies in classpath(or module path in 11+) if you wanna run this jar.

For more details, please learn more about [maven](https://maven.apache.org/) .

Thanks.
