### ISSUE TITLE
Jenkins解析报告编码异常

### ISSUE THREAD

**Issue by jameskkkk** [alibaba/p3c#648]
通过fat-jar包，执行：
`java -cp p3c-pmd.jar net.sourceforge.pmd.PMD -d /xxx/xxx -R rule/ali-comment.xml -f xml -r /xxx/p3c_report.xml`

生成报告，通过Jenkins解析报告：
`dir (DIR_PATH) {
    pmd canComputeNew: false, canRunOnFailed: true, defaultEncoding: 'UTF-8', healthy: '', pattern: 'report.xml', unHealthy: ''
}`

提示编码格式异常：
`org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 15; Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester3.Digester.parse(Digester.java:1642)
	at org.apache.commons.digester3.Digester.parse(Digester.java:1701)
	at hudson.plugins.pmd.parser.PmdParser.parse(PmdParser.java:68)
	at hudson.plugins.analysis.core.AbstractAnnotationParser.parse(AbstractAnnotationParser.java:54)
	at hudson.plugins.analysis.core.FilesParser.parseFile(FilesParser.java:323)
	at hudson.plugins.analysis.core.FilesParser.parseFiles(FilesParser.java:281)
	at hudson.plugins.analysis.core.FilesParser.parserCollectionOfFiles(FilesParser.java:232)
	at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:203)
	at hudson.plugins.analysis.core.FilesParser.invoke(FilesParser.java:31)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3085)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at hudson.remoting.Engine$1$$Lambda$14/771205805.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.apache.xerces.impl.io.UTF8Reader.invalidByte(Unknown Source)
	at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
	at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
	at org.apache.xerces.impl.XMLEntityScanner.skipChar(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	... 22 more`

经测试，报告编码格式为“UTF-8”，手动修改为“GBK”：
`<?xml version="1.0" encoding="GBK"?>`

同时修改Jenkins语句，通过GBK解析：
`dir (DIR_PATH) {
    pmd canComputeNew: false, canRunOnFailed: true, defaultEncoding: 'GBK', healthy: '', pattern: 'report.xml', unHealthy: ''
}`

可正常解析。

请问，如何修改为UTF-8支持？

**Comment by Yuyang105** [comment]
@smiler158 看一下哈

**Comment by smiler158** [comment]
看上去是jekins pmd插件解析编码的问题，可以看下插件源码那边如何同时兼容下UTF-8解析。另jekins插件也支持自己开发，可以写个插件去解析UTF-8的。
