### ISSUE TITLE
Idea 2020.1 启动后报插件异常

### ISSUE THREAD

**Issue by afsfge** [alibaba/p3c#652]
**Describe the bug**

Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1

java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:150)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:582)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.doGetService(PlatformComponentManagerImpl.kt:356)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:343)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
	at com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent.initComponent(CommonSettingsApplicationComponent.kt:40)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:234)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:335)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:335)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:184)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:832)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:311)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:416)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**To Reproduce**
1.安装idea2020.1 beta1版本
2.启动idea

**Expected behavior**
插件无异常

**Screenshots**
![image](https://user-images.githubusercontent.com/17295616/77130546-56f73600-6a93-11ea-9f68-6f78e0f8c0e2.png)

![image](https://user-images.githubusercontent.com/17295616/77130579-75f5c800-6a93-11ea-837b-6b379796a21f.png)

**Comment by byyxx128** [comment]
不要装中文语言包，用英文原版没事。中文包造成崩溃的不止这一个插件，只不过这个背黑锅了而已……

**Comment by afsfge** [comment]
> 不要装中文语言包，用英文原版没事。中文包造成崩溃的不止这一个插件，只不过这个背黑锅了而已……

我没有安装中文语言包，我用的就是英文原版

**Comment by byyxx128** [comment]
好吧，英文原版我也崩溃了一次，是启动之后加载项目之前……坐等修复。不过我估计短时间内不会修，毕竟2020.1离正式版遥遥无期还……就连2019.3还是去年12月才更新兼容的……

**Comment by afsfge** [comment]
idea2020.1今天发布rc版本了，一周内肯定发正式版了，现在插件还是启动及报错。。。

**Comment by byyxx128** [comment]
看看什么时候支持2019的吧……去年年底……支持2020版遥遥无期……（估计要今年年底……）

**Comment by byyxx128** [comment]
看看什么时候支持2019的吧……去年年底……支持2020版遥遥无期……（估计要今年年底……）
附：更新频率——
![image](https://user-images.githubusercontent.com/20079289/78223957-b858d500-7495-11ea-8ccc-0d5a75971962.png)
一年不超过三更，直到去年才把最低支持版本提高到2016，你还指望支持2020……想什么呢……

**Comment by XenoAmess** [comment]
我修了 阿里不merge 我有啥办法。
就懒懒呗。
https://github.com/alibaba/p3c/pull/655

**Comment by tomgao365** [comment]
管理人员反馈有些慢了。

**Comment by byyxx128** [comment]
自去年十月份以来就没啥comments……
![image](https://user-images.githubusercontent.com/20079289/78956241-3cedc800-7b14-11ea-91e2-cae4163a093b.png)
第一个人好像merge了好几个，我帮你@了一下……

**Comment by byyxx128** [comment]
自去年十月份以来就没啥commits……
![image](https://user-images.githubusercontent.com/20079289/78956241-3cedc800-7b14-11ea-91e2-cae4163a093b.png)
第一个人好像merge了好几个，我帮你@了一下……

**Comment by afsfge** [comment]
> 我修了 阿里不merge 我有啥办法。
> 就懒懒呗。
> #655

能不能本地直接打个包，发出来大家看下

**Comment by afsfge** [comment]
> 我修了 阿里不merge 我有啥办法。
> 就懒懒呗。
> #655

能不能本地打个包，我们测试下

**Comment by tomgao365** [comment]
哪位老兄 fork 一份搞个替代品。😀

**Comment by kyj117** [comment]
> 我修了 阿里不merge 我有啥办法。
> 就懒懒呗。
> #655

兄台可否打个包让大家用下😁

**Comment by XenoAmess** [comment]
https://github.com/XenoAmess/p3c/releases/tag/idea-plugin-2.0.1.1x

**Comment by afsfge** [comment]
> @tomgao365 @kyj117 @afsfgen @byyxx128
> https://github.com/XenoAmess/p3c/releases/tag/idea-plugin-2.0.1.1x
> 现在姑且先从github release发布吧。
> 
> 我已经往jetbrains那边提交了
> 如果审核通过的话 两天内应该可以从这边上线https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
> ——————————
> 如果他们没时间维护，那我就亲自动手。

很强，我试试

**Comment by XenoAmess** [comment]
> > @tomgao365 @kyj117 @afsfgen @byyxx128
> > https://github.com/XenoAmess/p3c/releases/tag/idea-plugin-2.0.1.1x
> > 现在姑且先从github release发布吧。
> > 我已经往jetbrains那边提交了
> > 如果审核通过的话 两天内应该可以从这边上线https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
> > ——————————
> > 如果他们没时间维护，那我就亲自动手。
> 
> 很强，我试试

有bug 从 issue给反馈或者call 我邮箱都行
这几天有考试，可能修不那么及时
但是一个月内肯定给你修了（如果在我水平范围内）

**Comment by byyxx128** [comment]
大佬威武！Jetbrains 已经审核通过了，今天不是 Good Friday 么竟然有人审核……估计都在家办公了，闲着也是闲着，就给你审核了……阿里这边维护太不及时了，最近的一次commit竟然是发招聘广告你敢信，放着一大堆pr看都不看，一堆issue也不检查……哎……

**Comment by zhshuixian** [comment]
我禁用了中文版插件就好了。2020.1 正式版

**Comment by SeanCai** [comment]
@afsfge @zhshuixian  新的 2.0.2 版本已经发布，审核通过后就可以下载了

**Comment by SeanCai** [comment]
@XenoAmess 不好意思，下次我们月会review一下，然后合进来，这次我先简单的修复了，也参考了一下你的分支代码，没有去注意pr
