### ISSUE TITLE
IDEA 2020.1  正式版本 异常

### ISSUE THREAD

**Issue by bpzhang** [alibaba/p3c#663]
java.lang.Throwable: Do not call commitAllDocumentsUnderProgress inside write-action
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocumentsUnderProgress(PsiDocumentManagerBase.java:229)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:92)
	at com.alibaba.p3c.idea.quickfix.AliQuickFix$Companion.doQuickFix(AliQuickFix.kt:75)
	at com.alibaba.p3c.idea.quickfix.LowerCamelCaseVariableNamingQuickFix.applyFix(LowerCamelCaseVariableNamingQuickFix.kt:44)
	at com.alibaba.p3c.idea.quickfix.LowerCamelCaseVariableNamingQuickFix.applyFix(LowerCamelCaseVariableNamingQuickFix.kt:30)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:70)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:186)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:244)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:246)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:221)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:220)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:119)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1454)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1450)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:152)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:326)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:111)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:184)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:134)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:106)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:255)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:461)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:415)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:356)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:269)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:370)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:350)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:93)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ZyqChina** [comment]
打开idea就报错,只能先禁用插件,赶紧修复呀

**Comment by jarvisqi** [comment]
看样子官方没有支持2020的样子，发布好几天了，我看提的issue也有好几个。

**Comment by ZyqChina** [comment]
> 看样子官方没有支持2020的样子，发布好几天了，我看提的issue也有好几个。
不能吧,应该是还没来得及支持呢

**Comment by ZyqChina** [comment]
> 看样子官方没有支持2020的样子，发布好几天了，我看提的issue也有好几个。

不能吧,应该还没来得及支持呢

**Comment by XenoAmess** [comment]
@bpzhang @ZyqChina @jarvisqi
https://github.com/alibaba/p3c/issues/652
官方目前没有表现出支持2020.1的意愿。
你可以用我的第三方维护版
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

**Comment by wxywizard** [comment]
> @bpzhang @zyqchina @jarvisqi
> #652
> 官方目前没有表现出支持2020.1的意愿。
> 你可以用我的第三方维护版
> https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

有啥区别吗？

**Comment by XenoAmess** [comment]
> > @bpzhang @zyqchina @jarvisqi
> > #652
> > 官方目前没有表现出支持2020.1的意愿。
> > 你可以用我的第三方维护版
> > https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
> 
> 有啥区别吗？

我每个版本都写更新日志了。
嗯大体上就是 支持了2020.1 然后修了点minor的bug（文档bug之类的） 然后merge了几个不重要的pr
然后把一些写的太恶臭的地方搞干净点。
没大改。

**Comment by JHXue** [comment]
等更新~

**Comment by wxywizard** [comment]
> 等更新~

感觉更新没影呢。。。

**Comment by honglujun** [comment]
> @bpzhang @zyqchina @jarvisqi
> #652
> 官方目前没有表现出支持2020.1的意愿。
> 你可以用我的第三方维护版
> https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

下载安装了，但是不生效

**Comment by XenoAmess** [comment]
> > @bpzhang @zyqchina @jarvisqi
> > #652
> > 官方目前没有表现出支持2020.1的意愿。
> > 你可以用我的第三方维护版
> > https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
> 
> 下载安装了，但是不生效

。。。我自己测过，jetbrains家的人也应该有跑过测试，照理说应该没啥问题啊。。。
。。。有报错日志没？

**Comment by honglujun** [comment]
> > > @bpzhang @zyqchina @jarvisqi
> > > #652
> > > 官方目前没有表现出支持2020.1的意愿。
> > > 你可以用我的第三方维护版
> > > https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
> > 
> > 
> > 下载安装了，但是不生效
> 
> 。。。我自己测过，jetbrains家的人也应该有跑过测试，照理说应该没啥问题啊。。。
> 。。。有报错日志没？
重启了几次之后就好了，是可以用的，谢谢

**Comment by SeanCai** [comment]
@bpzhang 用的是社区版还是 旗舰版呀？ 我刚刚自己试了下， 社区版没有问题

**Comment by bpzhang** [comment]
@SeanCai 还有版本区分呢？ 我就是用的官方发布的版本啊 不过现在换了 用的是 @XenoAmess  提供的 没有问题

**Comment by SeanCai** [comment]
@bpzhang 我用社区版没问题，用旗舰版的就不行。 看错误是因为 不能在project未打开的情况下修改 菜单的文案。  新的 2.0.2 版本已经发布，审核通过后就可以下载了
