### ISSUE TITLE
org.sonar.updatecenter.common.exception.PluginNotFoundException: The plugin 'java' required by 'pmd' is missing.

### ISSUE THREAD

**Issue by liqiulin1983** [alibaba/p3c#695]
sonarqube6.7.7    集成该插件报错：

org.sonar.updatecenter.common.exception.PluginNotFoundException: The plugin 'java' required by 'pmd' is missing.
        at org.sonar.updatecenter.common.PluginReferential.addOutgoingDependency(PluginReferential.java:140)
        at org.sonar.updatecenter.common.PluginReferentialManifestConverter.lambda$fromPluginManifests$0(PluginReferentialManifestConverter.java:60)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.sonar.updatecenter.common.PluginReferentialManifestConverter.fromPluginManifests(PluginReferentialManifestConverter.java:56)
        at org.sonar.server.plugins.PluginReferentialMetadataConverter.getInstalledPluginReferential(PluginReferentialMetadataConverter.java:45)
        at org.sonar.server.plugins.InstalledPluginReferentialFactory.init(InstalledPluginReferentialFactory.java:54)
        at org.sonar.server.plugins.InstalledPluginReferentialFactory.start(InstalledPluginReferentialFactory.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
        at org.sonar.ce.container.ComputeEngineContainerImpl.start(ComputeEngineContainerImpl.java:183)
        at org.sonar.ce.ComputeEngineImpl.startup(ComputeEngineImpl.java:45)
        at org.sonar.ce.app.CeServer$CeMainThread.startup(CeServer.java:167)
        at org.sonar.ce.app.CeServer$CeMainThread.attemptStartup(CeServer.java:154)
        at org.sonar.ce.app.CeServer$CeMainThread.run(CeServer.java:141)
Caused by: java.util.NoSuchElementException: Unable to find plugin with key java
        at org.sonar.updatecenter.common.PluginReferential.findPlugin(PluginReferential.java:87)
        at org.sonar.updatecenter.common.PluginReferential.addOutgoingDependency(PluginReferential.java:126)
        ... 25 common frames omitted

**Comment by Yuyang105** [comment]
@liqiulin1983 麻烦提供下更详细的版本信息和运行信息

**Comment by lzp492456131** [comment]
请教同样遇到这个问题，我的环境是8.5的sonar版本，用的是docker环境创建的
