### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by shuiyihan-work** [alibaba/p3c#837]
更不能更新下插件,IDEA 2021.1.3 (211.7628.21) 是极限了,不支持2021.2 (212.4746.52)版本

**Comment by shuiyihan-work** [comment]
顺便问一下,这个插件还有人维护嘛?

**Comment by yun-yun** [comment]
https://github.com/alibaba/p3c/issues/825#issuecomment-880928374
看这个回答

**Comment by dqylyln** [comment]
ide 2021.2不支持报错，无论是外部版本还是内部的aone-ide 都报错。

Plugin 'com.alibaba.p3c.smartfox' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Alibaba Java Coding Guidelines, id=com.alibaba.p3c.smartfox, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/Alibaba Java Coding Guidelines, version=2.1.0, package=null), packagePrefix=null, instanceId=83, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:89)
    at com.intellij.ide.a.m.f.a(f.java:93)
    at com.intellij.ide.a.m.bM.a(bM.java:310)
    at com.intellij.ide.a.m.bT.a(bT.java:278)
    at com.intellij.ide.a.m.bT.c(bT.java:171)
    at com.intellij.ide.a.m.bT.b(bT.java:81)
    at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
    at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
    at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.ide.a.m.bT.a(bT.java:80)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:83)
    at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)




Plugin 'AliP3CPlugin' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: 
                com.alibaba.smartfox.common.component.application.InitApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Aone-Idea, id=AliP3CPlugin, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/Aone-Idea, version=1.183.0.2021060716, package=null), packagePrefix=null, instanceId=106, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:89)
    at com.intellij.ide.a.m.f.a(f.java:93)
    at com.intellij.ide.a.m.bM.a(bM.java:310)
    at com.intellij.ide.a.m.bT.a(bT.java:278)
    at com.intellij.ide.a.m.bT.c(bT.java:171)
    at com.intellij.ide.a.m.bT.b(bT.java:81)
    at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
    at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
    at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.ide.a.m.bT.a(bT.java:80)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:83)
    at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by yun-yun** [comment]
> ide 2021.2不支持报错，不管是外部版本还是内部的aone-ide都报错。
> 
> 插入 'com.alibaba.p3c.smartfox' 失败 初始化并将被禁用。请重新启动 IntelliJ IDEA。
> 
> java.lang.ClassNotFoundException: com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
> PluginClassLoader(plugin= PluginDescriptor (name=Alibaba Java Coding)指南, id=com.alibaba.p3c.smartfox, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/Alibaba Java Coding 指南, version=2.1.0, package=null), packagePrefix=null, instanceId=83, state=active)
> at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
> at java.base/ java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
> at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
> at com .intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
> 在 com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
> 在 com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
> 在 com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
> 在 com.intellij.idea.ApplicationLoader$initApplication $2$1.accept(ApplicationLoader.kt)
> 在 java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
> 在 java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) )
> 在 java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
> 在 com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
> 在 com.intellij.idea.ApplicationLoader $initApplication$2.apply(ApplicationLoader.kt)
> 在 java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
> 在 java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
> 在 com.intellij .idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
> 在 java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
> 在 java.base/java.util.concurrent.CompletableFuture。 thenComposeAsync(CompletableFuture.java:2246)
> at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
> at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
> at java.base /jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 在 java.base/jdk.internal.reflect.NativeMethodAccessorImpl。调用(NativeMethodAccessorImpl.java:62)
> 在 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl。调用(DelegatingMethodAccessorImpl.java:43)
> 在 java.base/java.lang.reflect.Method。调用(Method.java:566)
> at com.intellij.idea.aa(a.java:89)
> at com.intellij.ide.amfa(f.java:93)
> at com.intellij.ide.ambM.a(bM. java:310)
> 在 com.intellij.ide.ambT.a(bT.java:278)
> 在 com.intellij.ide.ambT.c(bT.java:171)
> 在 com.intellij.ide.ambT.b(bT .java:81)
> 在 java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
> 在 java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
> 在 java。 base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl。调用(NativeMethodAccessorImpl.java:62)
> 在 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl。调用(DelegatingMethodAccessorImpl.java:43)
> 在 java.base/java.lang.reflect.Method。调用(Method.java:566)
> at com.intellij.ide.ambT.a(bT.java:80)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal .reflect.NativeMethodAccessorImpl。调用(NativeMethodAccessorImpl.java:62)
> 在 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl。调用(DelegatingMethodAccessorImpl.java:43)
> 在 java.base/java.lang.reflect.Method。调用(Method.java:566)
> at com.intellij.idea.MainImpl.start(MainImpl.java:83)
> at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283)
> at java.base/java .util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
> 在 java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 在 java.base/java.util.concurrent.CompletableFuture $AsyncSupply.run(CompletableFuture.java:1705)
> 在 java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
> 在 java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask .java:290)
> 在 java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 在 java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 在 java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 在 java.base/java.util .concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> 
> 插入 'AliP3CPlugin' 失败 初始化并将被禁用。请重新启动 IntelliJ IDEA。
> 
> java.lang.ClassNotFoundException:
> com.alibaba.smartfox.common.component.application.InitApplicationComponent
> PluginClassLoader(plugin=PluginDescriptor(name=Aone-Idea, id=AliP3CPlugin, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/Aone-Idea, version=1.183.0.2021060716, package=null), packagePrefix=null, instanceId=106, state=active)
> at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
> at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
> at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
> at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
> at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
> at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
> at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
> at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
> at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
> at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
> at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
> at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
> at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
> at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
> at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
> at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
> at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
> at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
> at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at com.intellij.idea.a.a(a.java:89)
> at com.intellij.ide.a.m.f.a(f.java:93)
> at com.intellij.ide.a.m.bM.a(bM.java:310)
> at com.intellij.ide.a.m.bT.a(bT.java:278)
> at com.intellij.ide.a.m.bT.c(bT.java:171)
> at com.intellij.ide.a.m.bT.b(bT.java:81)
> at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
> at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
> at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at com.intellij.ide.a.m.bT.a(bT.java:80)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at com.intellij.idea.MainImpl.start(MainImpl.java:83)
> at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283)
> at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
> at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
> at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
> at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 在 java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 在 java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 在 java.base/java.util .concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

已经有人fork仓库做了修复，看这个回答
https://github.com/alibaba/p3c/issues/825#issuecomment-880928374

**Comment by SeanCai** [comment]
新版已提交idea 审核，感谢大家支持
