### ISSUE TITLE
idea 2021.2 版本崩溃

### ISSUE THREAD

**Issue by NineSwordsMonster** [alibaba/p3c#839]
**Describe the bug**

**To Reproduce**
1. 打开 idea
2. See error

**Expected behavior**
正常启动

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.5 
 - Browser chrome
 - Version 

**Additional context**
idea 错误日志如下

```
2021-07-28 11:08:57,581 [   3843]  ERROR - llij.ide.plugins.PluginManager - com.intellij.diagnostic.PluginException: Fatal error initializing 'com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
            ' [Plugin: com.alibaba.p3c.smartfox] 
java.util.concurrent.CompletionException: com.intellij.diagnostic.PluginException: Fatal error initializing 'com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
            ' [Plugin: com.alibaba.p3c.smartfox]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
	at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
	at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.a.a(a.java:89)
	at com.intellij.ide.a.m.f.a(f.java:93)
	at com.intellij.ide.a.m.bM.a(bM.java:310)
	at com.intellij.ide.a.m.bT.a(bT.java:278)
	at com.intellij.ide.a.m.bT.c(bT.java:171)
	at com.intellij.ide.a.m.bT.b(bT.java:81)
	at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
	at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
	at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.ide.a.m.bT.a(bT.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:83)
	at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.diagnostic.PluginException: Fatal error initializing 'com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
            ' [Plugin: com.alibaba.p3c.smartfox]
	at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:515)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:387)
	at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	... 44 more
Caused by: java.lang.ClassNotFoundException: com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Alibaba Java Coding Guidelines, id=com.alibaba.p3c.smartfox, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.92/IntelliJ IDEA.app.plugins/Alibaba Java Coding Guidelines, version=2.1.0, package=null), packagePrefix=null, instanceId=62, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
	... 50 more
2021-07-28 11:08:57,610 [   3872]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2021.2  Build #IU-212.4746.92 
2021-07-28 11:08:57,615 [   3877]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-07-28 11:08:57,615 [   3877]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2021-07-28 11:08:57,621 [   3883]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Alibaba Java Coding Guidelines version: 2.1.0 
2021-07-28 11:08:57,622 [   3884]   INFO - e.plugins.DisabledPluginsState - Plugins to disable: [com.alibaba.p3c.smartfox] 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT -  
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - Plugin Error 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - Plugin 'com.alibaba.p3c.smartfox' failed to initialize and will be disabled. Please restart IntelliJ IDEA. 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT -  
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - java.lang.ClassNotFoundException: com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT -              PluginClassLoader(plugin=PluginDescriptor(name=Alibaba Java Coding Guidelines, id=com.alibaba.p3c.smartfox, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.4746.92/IntelliJ IDEA.app.plugins/Alibaba Java Coding Guidelines, version=2.1.0, package=null), packagePrefix=null, instanceId=62, state=active) 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254) 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441) 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380) 
2021-07-28 11:08:57,626 [   3888]   INFO -                         STDOUT - 	at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt) 
2021-07-28 11:08:57,627 [   3889]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) 
2021-07-28 11:08:57,628 [   3890]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) 
2021-07-28 11:08:57,628 [   3890]   INFO -                         STDOUT - 	at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107) 
2021-07-28 11:08:57,628 [   3890]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.idea.a.a(a.java:89) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.ide.a.m.f.a(f.java:93) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.ide.a.m.bM.a(bM.java:310) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.ide.a.m.bT.a(bT.java:278) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.ide.a.m.bT.c(bT.java:171) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.ide.a.m.bT.b(bT.java:81) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at com.intellij.ide.a.m.bT.a(bT.java:80) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
2021-07-28 11:08:57,629 [   3891]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at com.intellij.idea.MainImpl.start(MainImpl.java:83) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at com.intellij.idea.StartupUtil.lambda$start$16(StartupUtil.java:283) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) 
2021-07-28 11:08:57,630 [   3892]   INFO -                         STDOUT -  
2021-07-28 11:10:19,868 [  86130]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2021-07-28 11:10:19,875 [  86137]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 

```

**Comment by jinghongjiang** [comment]
用这个插件吧，非官方的，最新版可以用：https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

阿里这个插件估计废了，没人维护👀

**Comment by Marblog** [comment]
+1

**Comment by iamlijiu** [comment]
+1

**Comment by pnunu** [comment]
+1

**Comment by edge2012** [comment]
+1

**Comment by One-Odysseus** [comment]
+1

**Comment by tucke** [comment]
+1

**Comment by 1965214573** [comment]
我在pull里面找到了解决办法，在`C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\Alibaba Java Coding Guidelines\lib`目录中找到`p3c-idea-2.1.0.jar`，使用压缩软件打开它，找到META-INF目录下的p3c.xml，使用压缩软件自带的编辑，对该文件进行编辑：

``` xml
<idea-plugin>
    <application-components>
        <component>
            <implementation-class>com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent
            </implementation-class><!--这里的标签被换行了，让标签不换行就可以了-->
        </component>
    </application-components>
```
修改为：
``` xml
<idea-plugin>
    <application-components>
        <component>
            <implementation-class>com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent</implementation-class>
        </component>
    </application-components>
```

**Comment by fromciom** [comment]
谢谢楼上,修改后,终于恢复正常了.

**Comment by daisenrong** [comment]
啥时候更新一下啊？在不更新就换google的标准了

**Comment by SeanCai** [comment]
新版已提交idea 审核感谢

**Comment by shilohooo** [comment]
> 新版已提交idea 审核，感谢大家支持

感谢您的坚持
