### ISSUE TITLE
用命令行去过滤一些文件目录时，用-ignorelist有问题

### ISSUE THREAD

**Issue by jiangguilong2000** [alibaba/p3c#866]
在用以下命令行执行时，发现过滤功能有点问题
java -server -jar $PWD/p3c-pmd-2.1.1.jar -d  ../../../proj  -ignorelist ../../../proj/game/src/gen/,../../../proj/proto/   -f yahtml -property outputDir=report  -cache cache.log -shortnames -R rulesets/java/ali-exception.xml,rulesets/java/ali-oop.xml,rulesets/java/ali-flowcontrol.xml,rulesets/java/ali-naming.xml,rulesets/java/ali-extend.xml -r /home/build/pmd/report.html  -encoding UTF-8 > p3c.log 2>&1 &

-ignorelist 
严重: Problem with Ignore File Path

Mandatory arguments:
1) A java source code filename or directory
2) A report format
3) A ruleset filename or a comma-delimited string of ruleset filenames

是否多个目录的过滤用逗号隔开不支持？

换成单个目录
二月 21, 2021 6:07:30 下午 net.sourceforge.pmd.PMD internalGetApplicableFiles
严重: Problem with Ignore File
java.io.IOException: File '../../../proj/yorha-proto' exists but is a directory
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:291)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1805)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1838)
        at net.sourceforge.pmd.util.FileUtil.readFilelist(FileUtil.java:168)
        at net.sourceforge.pmd.PMD.internalGetApplicableFiles(PMD.java:417)
        at net.sourceforge.pmd.PMD.getApplicableFiles(PMD.java:366)
        at net.sourceforge.pmd.PMD.doPMD(PMD.java:212)
        at net.sourceforge.pmd.PMD.run(PMD.java:485)
        at net.sourceforge.pmd.cli.PMDCommandLineInterface.run(PMDCommandLineInterface.java:165)
        at net.sourceforge.pmd.PMD.main(PMD.java:455)

不知如何使用 这个参数？

**Comment by jiangguilong2000** [comment]
已经解决
