### ISSUE TITLE
Exception in plugin Alibaba Java Coding Guidelines

### ISSUE THREAD

**Issue by xjzhw** [alibaba/p3c#932]
java.lang.ArrayIndexOutOfBoundsException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:672)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:357)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:293)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:268)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$5(InspectionRunner.java:130)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.siyeh.ig.inheritance.MissingOverrideAnnotationInspection.buildFix(MissingOverrideAnnotationInspection.java:61)
	at com.alibaba.p3c.idea.inspection.standalone.AliMissingOverrideAnnotationInspection.buildFix(AliMissingOverrideAnnotationInspection.kt:68)
	at com.siyeh.ig.BaseInspectionVisitor.createFixes(BaseInspectionVisitor.java:225)
	at com.siyeh.ig.BaseInspectionVisitor.createAndInitFixes(BaseInspectionVisitor.java:210)
	at com.siyeh.ig.BaseInspectionVisitor.registerError(BaseInspectionVisitor.java:174)
	at com.siyeh.ig.BaseInspectionVisitor.registerError(BaseInspectionVisitor.java:167)
	at com.siyeh.ig.BaseInspectionVisitor.registerMethodError(BaseInspectionVisitor.java:111)
	at com.alibaba.p3c.idea.inspection.standalone.AliMissingOverrideAnnotationInspection$MissingOverrideAnnotationVisitor.visitMethod(AliMissingOverrideAnnotationInspection.kt:106)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:289)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:325)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:331)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	... 5 more

**Comment by xjzhw** [comment]
IDEA 2022.2
Build #IU-222.3345.118,built on July 26,2022

**Comment by xjzhw** [comment]
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to XXXXXXX
Subscription is active until September 24, 2022.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins:
    com.tabnine.TabNine (0.7.21)
    com.nasller.CodeGlancePro (1.4.9)
    ink.organics.pojo2json (1.2.5)
    de.kontext_e.idea.plugins.autofill (1.0)
    com.nnthink.aixcoder (4.0.7-2020)
    com.alibaba.p3c.smartfox (2.1.1)
    GsonFormatPlus (1.6.1)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    SequenceDiagram (2.2.0)
    com.tianlei.plugin.mybatis (2.1.2)
    izhangzhihao.rainbow.brackets (6.25)
    com.bruce.intellijplugin.generatesetter (2.8.1)
    cn.yiiguxing.plugin.translate (3.3.4)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by xjzhw** [comment]
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to XXXXXXX
Subscription is active until September 24, 2022.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins:
    com.tabnine.TabNine (0.7.21)
    com.nasller.CodeGlancePro (1.4.9)
    ink.organics.pojo2json (1.2.5)
    de.kontext_e.idea.plugins.autofill (1.0)
    com.nnthink.aixcoder (4.0.7-2020)
    com.alibaba.p3c.smartfox (2.1.1)
    GsonFormatPlus (1.6.1)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    SequenceDiagram (2.2.0)
    com.tianlei.plugin.mybatis (2.1.2)
    izhangzhihao.rainbow.brackets (6.25)
    com.bruce.intellijplugin.generatesetter (2.8.1)
    cn.yiiguxing.plugin.translate (3.3.4)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by mysmlz** [comment]
+1

**Comment by ltyeamin** [comment]
me too!

**Comment by ltyeamin** [comment]
IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022
Licensed to kiddy inseams
您有此版本的永久回退许可证。
订阅有效期至 2025年8月1日。
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 6
Non-Bundled Plugins:
    monokai-pro (1.9)
    leetcode-editor (8.3)
    com.nasller.CodeGlancePro (1.5.0)
    com.intellij.zh (222.202)
    com.biyusheng.plugins (2.2.0)
    com.alibaba.p3c.smartfox (2.1.1)
    GsonFormatPlus (1.6.1)
    SequenceDiagram (2.2.1)
    MavenRunHelper (4.21.222.2964.0)
    izhangzhihao.rainbow.brackets (6.25)
    com.baomidou.plugin.idea.mybatisx (1.5.4)
    com.bruce.intellijplugin.generatesetter (2.8.1)
    cn.yiiguxing.plugin.translate (3.3.5)

Kotlin: 222-1.7.10-release-334-IJ3739.54

**Comment by godfather1103** [comment]
https://github.com/alibaba/p3c/issues/900#issuecomment-1182951092

**Comment by mengjianjiandaoni** [comment]
+1

**Comment by zcbbpo** [comment]
+1

**Comment by dej4vu** [comment]
+1

**Comment by midsolo** [comment]
+1

**Comment by wingshadow** [comment]
+1

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-

**Comment by Rusnyz** [comment]
+1

**Comment by nightsleon** [comment]
+1
