### ISSUE TITLE
2023.1版本插件报错

### ISSUE THREAD

**Issue by a2501521908** [alibaba/p3c#970]
IDEA版本：
<img width="432" alt="image" src="https://user-images.githubusercontent.com/32430752/235334295-cce28d2d-efef-4744-b29b-abc5d1052b8b.png">
报错日志：
<img width="824" alt="image" src="https://user-images.githubusercontent.com/32430752/235334189-34707b5d-02b8-47e6-93d8-b71332e718ff.png">
我的IDEA版本是2023.1，更新了目前最新版本的插件版本：2.1.1，下面是堆栈信息：

```java
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 23,4,main] 622408301 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1233666557
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSet(WorkspaceFileIndexImpl.kt:180)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.isInContent(WorkspaceFileIndexImpl.kt:73)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:314)
	at com.alibaba.p3c.idea.action.PmdGlobalInspectionContextImpl$startIterateScopeInBackground$task$1$run$1.process(PmdGlobalInspectionContextImpl.kt:234)
	at com.alibaba.p3c.idea.action.PmdGlobalInspectionContextImpl$startIterateScopeInBackground$task$1$run$1.process(PmdGlobalInspectionContextImpl.kt:228)
	at com.intellij.openapi.vfs.CompactVirtualFileSet.process(CompactVirtualFileSet.java:233)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:281)
	at com.alibaba.p3c.idea.action.PmdGlobalInspectionContextImpl$startIterateScopeInBackground$task$1.run(PmdGlobalInspectionContextImpl.kt:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by cdgeass** [comment]
提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml

**Comment by ChenSino** [comment]
> 提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml

Connection failed

**Comment by ChenSino** [comment]
> 提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml
链接地址是不是搞错了，下载这个可以用
https://github.com/cdgeass/p3c/releases/download/v2.1.2/Alibaba.Java.Coding.Guidelines-2.1.2.zip

**Comment by cdgeass** [comment]
> > 提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml
> > 链接地址是不是搞错了，下载这个可以用
> > https://github.com/cdgeass/p3c/releases/download/v2.1.2/Alibaba.Java.Coding.Guidelines-2.1.2.zip

确实写错了🥲

**Comment by a2501521908** [comment]
> > > 提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml
> > > 链接地址是不是搞错了，下载这个可以用
> > > https://github.com/cdgeass/p3c/releases/download/v2.1.2/Alibaba.Java.Coding.Guidelines-2.1.2.zip
> 
> 确实写错了🥲
老哥有权限搞到插件市场么

**Comment by a2501521908** [comment]
> 提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml

老哥有没有想法搞到插件市场，这样针对IDEA配置的云同步可以更完善一些～

**Comment by kusiru** [comment]
都几年没更新了，该放弃这个了

**Comment by sandangjia** [comment]
不止是用不了，安装后输入中文还会有严重的卡顿延迟

**Comment by sandangjia** [comment]
> 



> > 提了PR不过应该没人维护了。我做了个私仓，插件设置->管理插件仓库 添加 https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml
> > 链接地址是不是搞错了，下载这个可以用
> > https://github.com/cdgeass/p3c/releases/download/v2.1.2/Alibaba.Java.Coding.Guidelines-2.1.2.zip
> 
> 
> > I have a PR, but no one should be able to maintain it. I made a private warehouse, plug-in settings->manage plug-in repository Add https://cdgeass.com/jetbrains/alibaba-java-coding-guidelines/updatePlugins.xml
> > The link address is not wrong, download this can be used
> > https://github.com/cdgeass/p3c/releases/download/v2.1.2/Alibaba.Java.Coding.Guidelines-2.1.2.zip

能用吗？用了2022版本的插件，会导致输入中文卡顿，并且使用有问题

**Comment by wangjia2016** [comment]
现在这个插件没人维护了

**Comment by godfather1103** [comment]
https://github.com/alibaba/p3c/issues/900#issuecomment-1523259107
可以试一下这个，安装之前先卸载官方插件

**Comment by godfather1103** [comment]
https://github.com/alibaba/p3c/issues/900#issuecomment-1656501503
这个修复了2023.2打开报错的问题，上面修复2023.1的EDT报错

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-

**Comment by a2501521908** [comment]
> https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-
```java
com.intellij.diagnostic.PluginException: Cannot create extension (class=com.alibaba.p3c.idea.listener.MyProjectStartupActivity) [Plugin: io.github.godfather1103.alibaba.p3c]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1057)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:587)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: com.alibaba.p3c.idea.listener.MyProjectStartupActivity
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:220)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1528)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:947)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	... 10 more

```

目前看起来启动还是报错啊，大佬
<img width="695" alt="image" src="https://github.com/alibaba/p3c/assets/32430752/694ae3a1-8cc2-45cd-a838-e734515c28c2">

**Comment by godfather1103** [comment]
先卸载原来安装的官方版本，再安装我的，两个插件一起的话会冲突

**Comment by a2501521908** [comment]
> 先卸载原来安装的官方版本，再安装我的，两个插件一起的话会冲突

看起来是的，启动不会报错了，我把官方的插件禁用了都不可以☹️，只能卸载
