### ISSUE TITLE
2023.2版本插件报错

### ISSUE THREAD

**Issue by fenglangjunzi** [alibaba/p3c#980]
com.intellij.diagnostic.PluginException: Please, do not use constructor injection: it slows down initialization and may lead to performance problems (requestorClass=com.alibaba.p3c.idea.component.AliProjectComponent)). See https://plugins.jetbrains.com/docs/intellij/plugin-services.html for details. [Plugin: com.alibaba.p3c.smartfox]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:111)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:82)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:36)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:446)
	at com.intellij.openapi.project.impl.ProjectManagerImplKt$initProject$2$2.invokeSuspend(ProjectManagerImpl.kt:1227)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

<img width="1294" alt="image" src="https://github.com/alibaba/p3c/assets/5000975/7224389a-d256-476e-9dfa-74f197c93165">

**Comment by godfather1103** [comment]
#900

**Comment by godfather1103** [comment]
https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-

**Comment by fenglangjunzi** [comment]
> https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-

这算是民间修复吗？官方不迭代了？

**Comment by godfather1103** [comment]
从2022.1版本开始就有问题了，官方一直没更新，发PR也没人接收，我只能自己改了上传市场，方便自己使用

**Comment by fenglangjunzi** [comment]
作者莫非也毕业了吗😿

**Comment by jueding920** [comment]
这个不再更新了吗？

**Comment by shawshineeast** [comment]
> https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-

大佬可以维护一个仓库吗

**Comment by godfather1103** [comment]
> > https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-
> 
> 大佬可以维护一个仓库吗

什么意思？

**Comment by shawshineeast** [comment]
> > > https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-
> > 
> > 
> > 大佬可以维护一个仓库吗
> 
> 什么意思？

就是弄一个 git 地址，大家一起来维护，这个插件目前好像没人维护了

**Comment by godfather1103** [comment]
> > > > https://plugins.jetbrains.com/plugin/22381-alibaba-java-coding-guidelines-fix-some-bug-
> > > 
> > > 
> > > 大佬可以维护一个仓库吗
> > 
> > 
> > 什么意思？
> 
> 就是弄一个 git 地址，大家一起来维护，这个插件目前好像没人维护了

一直都有啊https://github.com/godfather1103/p3c

**Comment by godfather1103** [comment]
https://github.com/godfather1103/p3c/issues/4
https://github.com/godfather1103/p3c/releases/tag/1.3-2023.2-2.1.1
增加了自定义namelist.properties的功能

**Comment by a1243412811** [comment]
> [godfather1103/p3c#4](https://github.com/godfather1103/p3c/issues/4) https://github.com/godfather1103/p3c/releases/tag/1.3-2023.2-2.1.1 增加了自定义namelist.properties的功能

老哥idea更新了 用不了你的插件了 辛苦更新一下呗

**Comment by godfather1103** [comment]
@a1243412811 等官方审核，也可以去这边下载，离线安装最新版https://github.com/godfather1103/p3c/issues/23#issuecomment-1844243007
